project_name: lorawan-network-server

builds:
  - main: cmd/lorawan-network-server/main.go
    binary: lorawan-network-server
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

release:
  disable: true

nfpm:
  vendor: Lorawan 
  homepage: https://www.lorawan.io/
  maintainer: somebody <me@somebody.com>
  description: Lorawan Network Server
  license: MIT
  formats:
    - deb
    - rpm
  bindir: /usr/bin
  files:
    "packaging/files/lorawan-network-server.rotate": "/etc/logrotate.d/lorawan-network-server"
    "packaging/files/lorawan-network-server.init": "/usr/lib/lorawan-network-server/scripts/lorawan-network-server.init"
    "packaging/files/lorawan-network-server.service": "/usr/lib/lorawan-network-server/scripts/lorawan-network-server.service"
    "packaging/files/lorawan-network-server-eu868.toml": "/etc/lorawan-network-server/examples/lorawan-network-server-eu868.toml"
    "packaging/files/lorawan-network-server-us915.toml": "/etc/lorawan-network-server/examples/lorawan-network-server-us915.toml"
  config_files:
    "packaging/files/lorawan-network-server.toml": "/etc/lorawan-network-server/lorawan-network-server.toml"
  scripts:
    preinstall: "packaging/scripts/pre-install.sh"
    postinstall: "packaging/scripts/post-install.sh"
    postremove: "packaging/scripts/post-remove.sh"
