version: "2"
services:
  lorawan-network-server:
    build:
      context: .
      dockerfile: Dockerfile-devel
    command: make serve
    volumes:
      - ./:/lorawan-network-server
    links:
      - postgres
      - redis
      - mosquitto
      - rabbitmq
    environment:
      - DB_AUTOMIGRATE=true
      - NET_ID=010203
      - BAND=EU868
      - REDIS_URL=redis://redis:6379
      - GW_MQTT_SERVER=tcp://mosquitto:1883
      - GW_SERVER_JWT_SECRET=verysecret
      - POSTGRES_DSN=postgres://lorawan_ns:lorawan_ns@postgres/lorawan_ns?sslmode=disable
      - TEST_POSTGRES_DSN=postgres://lorawan_ns:lorawan_ns@postgres/lorawan_ns?sslmode=disable
      - TEST_REDIS_SERVERS=redis:6379
      - TEST_MQTT_SERVER=tcp://mosquitto:1883
      - TEST_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=lorawan_ns
      - POSTGRES_USER=lorawan_ns
      - POSTGRES_DB=lorawan_ns

  redis:
    image: redis:6-alpine

  mosquitto:
    image: eclipse-mosquitto:1.6

  rabbitmq:
    image: rabbitmq:3-alpine
